### ISSUE TITLE
How do I solve this problem?

### ISSUE THREAD

**Issue by 667Labs** [maximedrn/opensea_automatic_uploader#17]
I am facing the following problem. Everything is working perfectly, metamask connects but in picture it stays on screen but does not confirm, metamask stays on screen but connects.

It gives the error in the image below. Where am I doing wrong, I am following all the instructions.

_`DevTools listening on ws://127.0.0.1:50123/devtools/browser/97e1f415-4f58-438b-854c-de9f58c2b9df
Login to MetaMask. Logged to Metamask.
Login to Opensea. Login to Opensea failed. Retrying.
Traceback (most recent call last):
  File "C:\Users\Eray\Desktop\opensea\opns\main.py", line 305, in opensea_login
    web.tab_changes(2)  # Switch to the MetaMask popup tab.
  File "C:\Users\Eray\Desktop\opensea\opns\main.py", line 237, in tab_changes
    WDW(self.driver, 15).until(  # Wait the tabs lists to be different.
  File "C:\Users\Eray\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Eray\Desktop\opensea\opns\main.py", line 616, in <module>
    opensea.opensea_login()  # Connect to Opensea.
  File "C:\Users\Eray\Desktop\opensea\opns\main.py", line 315, in opensea_login
    WDW(web.driver, 15).until(EC.number_of_windows_to_be(2))
  File "C:\Users\Eray\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

C:\Users\Eray\Desktop\opensea\opns>`_

![1](https://user-images.githubusercontent.com/96050930/147380455-954b47b7-5480-46fa-84b7-b9746e04efb6.JPG)

**Comment by 667Labs** [comment]
Even though I sort of solved the problem, it gives the error in the picture below when it adds
![2](https://user-images.githubusercontent.com/96050930/147380689-34a158ca-83a2-48c1-95cc-a92bac77131f.JPG)

**Comment by emielmaters** [comment]
The uploading part works well, but when it hits the create button I get the same error page.
But also a little different error I think:
![afbeelding](https://user-images.githubusercontent.com/37311615/147403429-dcb71288-4998-4e3d-94dc-e1d14919dd30.png)
Can't see what causes this to occurs.

**Comment by maximedrn** [comment]
Hello, sometimes the bot crashes when it arrives at the login to Opensea: the MetaMask contract can't be signed. You have to restart the bot until it works (2 or 3 times maximum).

Moreover, I corrected the problem after the upload to go to the sale part.
You have to replace this line (**417**):
```python
web.visible('//div[@role="dialog"]')  # Check if it's uploaded.
```
with this:
```python
WDW(web.driver, 30).until(lambda _: web.driver.current_url !=
                                      self.create_url + '?enable_supply=true')
```
I advise you to wait a few days before uploading and selling your NFTs with my bot, I have encountered other problems that I am in the process of fixing. Thank you for your interest in this project :)

**Comment by emielmaters** [comment]
Looks like your new code is working! I am going to test it with some quickly made NFT's.
