### ISSUE TITLE
session not created: This version of ChromeDriver only supports Chrome version 94

### ISSUE THREAD

**Issue by ChrisBomBom** [maximedrn/opensea_automatic_uploader#19]

**Comment by maximedrn** [comment]
Open your Chrome browser. In the search bar type:
```
chrome://settings/help
```
and look at the browser version.
<a data-flickr-embed="true" href="https://www.flickr.com/photos/193272760@N05/51782427033/in/dateposted-public/" title="Paramètres – À propos de Chrome"><img src="https://live.staticflickr.com/65535/51782427033_6090735588_k.jpg"  alt="Paramètres – À propos de Chrome"></a>

Then on [ChromeDriver](https://chromedriver.chromium.org/downloads), select the driver that corresponds to the version, then download the one that corresponds to your operating system:
* ``chromedriver_linux64.zip`` for Linux.
* ``chromedriver_mac64.zip`` for MacOS.
* ``chromedriver_mac64_m1.zip`` for MacOS with M1 processor.
* ``chromedriver_win32.zip`` for Windows.

Extract the executable and move it in the ``opensea_automatic_uploader-master/assets/`` directory.
If you use Linux or MacOS, you may have to change the path in the ``main.py`` file from:
```python
self.webdriver_path = os.path.abspath('assets/chromedriver.exe')   # Line 174 or the file.
```
to:
```python
self.webdriver_path = os.path.abspath('assets/chromedriver')
```
