### ISSUE TITLE
Additional signature

### ISSUE THREAD

**Issue by niking00** [maximedrn/opensea_automatic_uploader#22]
After:
`web.clickable('//button[@type="submit"]')`

A confirmation window appears, not provided for in the code:
![изображение](https://user-images.githubusercontent.com/64714042/147568793-d37b5087-9b84-45e6-81ce-c81e78a8c0fa.png)

What needs to be done to avoid this or how to take it into account?
_(After clicking the button, you need to sign a metamask contract)_

**Comment by maximedrn** [comment]
Hi! I've uploaded a new version. You can know sign the MetaMask contract for listing your NFT :)
You just have to deposit first ETH or MATIC on your wallet then the sale will work 100%.
