### ISSUE TITLE
How to add autopath in json

### ISSUE THREAD

**Issue by ChotaVeer** [maximedrn/opensea_automatic_uploader#31]
I'm using HashLips Art Engine. But they do not have similar codes just like you. So If I have to upload all the nfts I have to copy and paste each JSON from HashLips Art Engine to yours. Is there a way that I can combine both JSON files or generate your required JSON from HashLips Art Engine?
Please help me you did a really great work for us

**Comment by maximedrn** [comment]
Can you send me the JSON file generated by the HashLips art engine or a part of it.
I can try to create an automatic conversion robot. Otherwise, you will have to do it manually by copying/pasting your metadata.

**Comment by gatekendo** [comment]
> Saya menggunakan Mesin Seni HashLips. Tetapi mereka tidak memiliki kode yang sama seperti Anda. Jadi, jika saya harus mengunggah semua nfts, saya harus menyalin dan menempelkan setiap JSON dari HashLips Art Engine ke milik Anda. Apakah ada cara saya dapat menggabungkan kedua file JSON atau menghasilkan JSON yang Anda butuhkan dari HashLips Art Engine? Tolong bantu saya, Anda melakukan pekerjaan yang sangat hebat untuk kami

send your json files to me... i will convert your json files to xls

**Comment by ChrisBomBom** [comment]
> Can you send me the JSON file generated by the HashLips art engine or a part of it. I can try to create an automatic conversion robot. Otherwise, you will have to do it manually by copying/pasting your metadata.

Lol Bro we have a 10.000 Meta DATA!
