### ISSUE TITLE
Imported secondary account

### ISSUE THREAD

**Issue by ckarmy** [maximedrn/opensea_automatic_uploader#36]
By default the bot log in with my account 01 but I have paid the gas fee with imported account 02. How can I select a specific account?

Thanks!

**Comment by maximedrn** [comment]
If you want to switch to your second account you can delete the ``assets/password.txt`` and ``assets/recovery_phrase.txt``.
Then, the bot will ask you to input your credentials.

**Comment by ckarmy** [comment]
The second account is from the same recovery_phrase. I imported via secret key :(

**Comment by maximedrn** [comment]
Is it necessary to be connected on the account that doesn't have paid gas fee? You could just connect on the other one and start your NFT listing. Normally, if you have the same MetaMask account connected to the 2 Opensea accounts, the gas fee is already paid for the 2 accounts.

**Comment by ckarmy** [comment]
I try but opensea ask to pay the initialize wallet fee...

**Comment by maximedrn** [comment]
I'm sorry, I cannot do anything. Is Opensea allows you to chose your account?

**Comment by ckarmy** [comment]
![image](https://user-images.githubusercontent.com/10090783/149003841-9ae4d8db-abe2-4d30-8adb-c0b033fc1ab9.png)

I need to connect to ckamryg account but always connect to account 02. I will try to modify main.py

**Comment by maximedrn** [comment]
In ``self.opensea_sale()`` method, you can add 2 ``web.clickable()`` with the XPATH of this selector (Profile picture button and account element from list). This 2 clicks will be after the switch to the MetaMask pop up.
I'll try to integrate this in the future updates.
Thank you :)

**Comment by ckarmy** [comment]
I solved adding this to metamask_login():

`
            web.clickable('//*[contains(@class, "btn-primary")][position()=1]')
            web.clickable('//*[contains(@class, "popover-header__button")][position()=1]')
            web.clickable('//*[contains(@class, "account-menu__icon")][position()=1]')
            web.clickable('//*[contains(@class, "account-menu__item account-menu__item--clickable")][position()=2]')
            web.send_keys('//*[@id="private-key-box"]', "xxxxxxxxxxxx")
            web.clickable('//*[contains(@class, "btn-secondary")][position()=1]')`
