### ISSUE TITLE
Polygon to Ethereum

### ISSUE THREAD

**Issue by ElHuervolar** [maximedrn/opensea_automatic_uploader#38]
Hey! How to change the polygon to Ethereum?

**Comment by maximedrn** [comment]
In your file you have to change Polygon to Ethereum.
On Opensea, if your NFT is already uploaded, you can't. You need to re-upload the NFT.

**Comment by ElHuervolar** [comment]
> In your file you have to change Polygon to Ethereum. On Opensea, if your NFT is already uploaded, you can't. You need to re-upload the NFT.

Can you please in more detail?
In which file and what to change. I'm not a programmer)
Maybe here?
https://github.com/maximedrn/opensea_automatic_uploader/blob/master/main.py#:~:text=cannot%20be%20clicked.%27)-,try,-%3A%20%20%23%20Polygon%20blockchain%20requires

**Comment by ElHuervolar** [comment]
> In your metadata file (CSV, XLSX, JSON), you have a Blockchain column. Change it from Polygon to Ethereum.

first time I see such quick answers) thanks!
one more question, could you make a script to remove nft from opensea? remove 200 nft from 10000 and reload

**Comment by maximedrn** [comment]
It can be possible but it takes time. I add this feature to my list :)

**Comment by ElHuervolar** [comment]
super! I will follow you) and donate if successful in sales;)
