### ISSUE TITLE
Properties being appended with letter A

### ISSUE THREAD

**Issue by PurpleDonkey858** [maximedrn/opensea_automatic_uploader#39]
This is a really excellent piece of work. 

I'm having some trouble with the properties in both the .csv and .xlsx. No matter what I put in (even tried with escape characters) it appends the letter A to the trait description. For example:

[["Dog", "Male"], ["Cat", "Female"]]

Shows up as:
![mf2](https://user-images.githubusercontent.com/50408863/149355239-b1d30d45-57e8-4adf-a4bb-1d3d641f1518.png)

I ensured the text encoding was UTF-8 as the Python script expects.

Any ideas?
Thanks

**Comment by PurpleDonkey858** [comment]
it's also the same with just
[["Dog", "Male"]]

**Comment by maximedrn** [comment]
Are you running MacOS or Linux? The problem is with the ``clear_text()`` method. It sends a ``Ctrl``+``A`` or ``Command``+``A`` to delete the default text, so it may not work on other platforms besides Windows.

**Comment by PurpleDonkey858** [comment]
I'm running on Linux so that could well be the problem. Thanks

**Comment by PurpleDonkey858** [comment]
Apologies for the delay - that has fixed it. Thank You very much.
