### ISSUE TITLE
Syntax Error on MacOS. 

### ISSUE THREAD

**Issue by nothingatall200** [maximedrn/opensea_automatic_uploader#45]
What's the issue here? 
Problem seems to be "**:**" 

File "main.py", line 41
    def __init__(self, path: str) -> None:
                       
SyntaxError: invalid syntax

**Comment by maximedrn** [comment]
Did you change anything in the file? Line 41 of the file is:
```python
    def __init__(self, path: str) -> None:
```

Else, what is you Python version? Type one the command below:
```
python --version
```
```
python3 --version
```
If you only have Python 2.X installed (default version of Python on MacOS), you need to [upgrade to 3.7+](https://www.python.org/downloads/macos/) (3.9.9 is recommended).

**Comment by nothingatall200** [comment]
Hello and thank you for your reply. The newest version is installed…

**Comment by maximedrn** [comment]
I tried with a MacOS Catalina on a virtual machine and it worked. It's weird.
Try running the bot by typing:
```
python3 main.py
```
And not:
```
python main.py
```

**Comment by nothingatall200** [comment]
Thank you. I have also tried this already ;)

**Comment by maximedrn** [comment]
And it works?
