### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by allenfrostline** [maximedrn/opensea_automatic_uploader#54]
This is what I see after running `python3 main.py` with just 1 NFT to test:

```
Login to MetaMask. Logged to Metamask.
Login to Opensea. Logged to Opensea.

Uploading NFT n°1/1. An error occured.

All done! Your NFTs have been uploaded/sold.
```

Nothing has happened on Opensea or Metamask. Ideas? Also an intuitive suggestion is to optionally turn on debug mode for error details etc.

**Comment by gch4n69** [comment]
maybe opensea got an error. Not the code.

**Comment by maximedrn** [comment]
Hi! Can you send me the content of the file used please.

**Comment by allenfrostline** [comment]
As an update, I am now seeing login error (which is before the original error message above) with the following on page
```
Checking your browser before accessing opensea.io.
This process is automatic. Your browser will redirect to your requested content shortly.

Please allow up to 5 seconds…

DDoS protection by Cloudflare
```
The page keeps retrying and never got away from the 5 seconds.

**Comment by maximedrn** [comment]
> Hi @maximedrn with NFT related info hidden, here's the json config file I used:
> 
> ```json
> {
>     "nft":
>     [
>         {
>             "file_path": "~/Documents/Projects/OpenseaUploader/data/build/1.png",
>             "nft_name": "██████",
>             "external_link": "██████",
>             "description": "",
>             "collection": "██████", // I can't see what is written but be sure that it's correctly written.
>             "properties":  // change this.
>             {
>                 "background rarity": "original",
>                 "bottom rarity": "original",
>                 "top rarity": "original",
>                 "head rarity": "super rare"
>             },
>             "levels": "",
>             "stats": "",
>             "unlockable_content": "",
>             "explicit_and_sensitive_content": "",
>             "supply": 1,
>             "blockchain": "Ethereum",
>             "sale_type": "Fixed Price",
>             "price": 0.01,
>             "method": "",
>             "duration": "6 month", // 6 months is not available for now.
>             "specific_buyer": "",
>             "quantity": 1
>         }
>     ]
> }
> ```

Your metadata file is incorrect. Follow the examples in the `data/` folder.

**Comment by allenfrostline** [comment]
@maximedrn Thanks wrapping `properties` with a list and changing `duration` to 1 month fixed the original issue. However the sale still got cancelled in the end and after some research I think it because it's defaulting to my first wallet available on MetaMask while I was trying to use the second one. Is there any way I can edit `main.py` to choose the second available wallet instead? Thank you 🙏🏻

**Comment by maximedrn** [comment]
It is possible. After the bot has switched to the MetaMask pop up (`self.windows_handle(2)`), you need to click on the rounded profile image with the `self.clickable('[XPATH]')` method and then on the address you want in the list with the same method.

To get the XPATH, press `Ctrl` + `Shift` + `i`, then right click on the item and select `Inspect`. Finally, right click on the HTML element and select `Copy` -> `XPATH`.
