### ISSUE TITLE
URGENT HELP!!!!!!

### ISSUE THREAD

**Issue by newbie-123456789** [maximedrn/opensea_automatic_uploader#56]
IT IS SHOWING THIS AS SOON AS I CLICK '2' WHEN THE OPTION COMES OF METADATA  --->

Traceback (most recent call last):
  File "C:\Users\POOJAN PANDYA\Desktop\nft by cloud\new folder\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 574, in <module>
    settings = Settings(file, os.path.splitext(file)[1])
  File "C:\Users\POOJAN PANDYA\Desktop\nft by cloud\new folder\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 35, in __init__
    self.file = loads(open(file, encoding='utf-8').read())['nft']
TypeError: list indices must be integers or slices, not str

**Comment by maximedrn** [comment]
Is your file look like this?
```json
{
     "nft": [
       {
         "file_path": "",
         "nft_name": "",
         "external_link": "",
         "description": "",
         "collection": "",
         "properties": [
           {
             "type": "",
             "name": ""
           }
         ],
         "levels": [
           {
             "name": "",
             "from": 0,
             "to": 0
           }
         ],
         "stats": [
           {
             "name": "",
             "from": 0,
             "to": 0
           }
         ],
         "unlockable_content": [
           true,
           ""
         ],
         "explicit_and_sensitive_content": false,
         "supply": 1,
         "blockchain": ""
       }
     ]
   }
```
