### ISSUE TITLE
Stuck at Captcha / Not Able to Login

### ISSUE THREAD

**Issue by alimohsenbh** [maximedrn/opensea_automatic_uploader#57]
I get stuck at captcha not being able to login to OpenSea, even If I try to solve it manually it keeps asking again to verify.

I'm able to log in using chrome normally but not with the chrome driver, How to avoid this?

**Comment by alimohsenbh** [comment]
<img width="1440" alt="Screen Shot 2022-01-20 at 1 41 06 AM" src="https://user-images.githubusercontent.com/98060953/150230078-4aadd21e-cd14-41bf-b62b-28ec253d2a36.png">

**Comment by maximedrn** [comment]
Hi, Opensea now uses hCaptchas. I don't know if they will be present all the time. I will integrate a solution in the next few days.
