### ISSUE TITLE
Cannot Login Metamask

### ISSUE THREAD

**Issue by gatekendo** [maximedrn/opensea_automatic_uploader#58]
just login of the create page....always reload

**Comment by gch4n69** [comment]
Same here. Stuck at Signature request. 
https://imgur.com/teFtbCp

**Comment by gch4n69** [comment]
> It works on my side. Try to run the robot again, it should work.

I've download again your latest code but result still the same. Reload login and Stuck at "Signature Request"
https://imgur.com/fBqWtbt

**Comment by ChotaVeer** [comment]
Still waiting for your help..... Waiting to upload my collection

**Comment by maximedrn** [comment]
Hi! I have released a new version, I need feedback as I am fixing this problem blindly as I do not encounter any errors during the connection.
