### ISSUE TITLE
keep cannot login metamask

### ISSUE THREAD

**Issue by gatekendo** [maximedrn/opensea_automatic_uploader#61]
your last update keep cant login to opensea...just keep reload in login page

**Comment by gch4n69** [comment]
Keep reload in "Signing Request"?

**Comment by gatekendo** [comment]
> Keep reload in "Signature Request"?

yes...always reload on signature request

**Comment by maximedrn** [comment]
Please send me a video. I'll work on it.

**Comment by gatekendo** [comment]
> Tolong kirimkan saya video. Saya akan mengerjakannya.

https://user-images.githubusercontent.com/78825059/150596236-5828a7c3-72b7-4e80-a0db-732c9a660ec3.mp4

**Comment by maximedrn** [comment]
Hi! I have released a new version, I need feedback as I am fixing this problem blindly as I do not encounter any errors during the connection.
