### ISSUE TITLE
NFT sale cancelled

### ISSUE THREAD

**Issue by alimohsenbh** [maximedrn/opensea_automatic_uploader#62]
Hello,

I'm always getting NFT Sale Cancelled, upload is fine but sale is not happening.

My JSON format below:

            "supply": "1",
            "blockchain": "Polygon",
            "sale_type": "Fixed Price",
            "price": 0.01,
            "method": [""],
            "duration": ["6 months"],
            "specific_buyer": false,
            "quantity": "1"

Is there anything wrong in the format?

**Comment by gch4n69** [comment]
You can try change duration not 6 Month.

**Comment by maximedrn** [comment]
Supply and quantity must be 1 and not "1"

**Comment by maximedrn** [comment]
> You can try change duration not 6 Month.

Yes 👍

**Comment by mpi42** [comment]
so is a fixed price on polygon not possible? everything i tried failed here at line 179 self.duration -> list index out of range
any change to get the fixed price working on polygon?

**Comment by gch4n69** [comment]
> so is a fixed price on polygon not possible? everything i tried failed here at line 179 self.duration -> list index out of range any change to get the fixed price working on polygon?

You can try file .xlsx , I tried file in xlsx was working with fixed price in polygon

**Comment by maximedrn** [comment]
> so is a fixed price on polygon not possible? everything i tried failed here at line 179 self.duration -> list index out of range any change to get the fixed price working on polygon?

You get an error with the duration. You must have something like this:
```json
"duration": ["21-01-2022 18:00", "21-02-2022 18:00"],
```
XLSX: `["21-01-2022 18:00", "21-02-2022 18:00"]`
CSV: `["21-01-2022 18:00", "21-02-2022 18:00"];;`
In addition, the Polygon blockchain does not require a Sales Type or Method, they must be empty.
