### ISSUE TITLE
Stopped at opensea upload page

### ISSUE THREAD

**Issue by HiHdrl** [maximedrn/opensea_automatic_uploader#65]
Hi thanks for providing us this code! but i have a problem during the process of uploading the nft to opensea

the message i received
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\opensea_automatic_uploader-master\main.py", line 714, in <module>
    structure.get_data(nft_number)  # Structure the data of the NFT.
  File "C:\Users\Admin\Documents\opensea_automatic_uploader-master\main.py", line 104, in get_data
    eval('self.structure_' + self.extension + '()')
  File "<string>", line 1, in <module>
  File "C:\Users\Admin\Documents\opensea_automatic_uploader-master\main.py", line 112, in structure_json
    self.structure_data([self.dict_to_list(
  File "C:\Users\Admin\Documents\opensea_automatic_uploader-master\main.py", line 179, in structure_data
    self.duration: list or str = nft_data[15 - index]
IndexError: list index out of range.

yesterday the code was not working to login in to opensea and now when i tried it again and it worked!
also thank you!

edit: so i tried the code again and yeah the same issue i got from yesterday which couldn't login to opensea its back again, and
i notice on a different post someone talk about it so i'll be patiently waiting for the fix and again thank you very much!

**Comment by maximedrn** [comment]
Hello, the first problem is caused by your metadata file. You get a "list index out of range" error, which means that you have less data than you need. Can you send me an extract of your metadata file please?

For the Opensea login, I'm working on a solution, it's because your PC/connection (or the Opensea servers) are a bit slow and the MetaMask "Sign in" pop up takes 1 or 2 seconds to appear.

**Comment by HiHdrl** [comment]
hi thank you for the respond so i have just add more things to the metadata like it said here (https://github.com/maximedrn/opensea_automatic_uploader/blob/master/data/json_structure_upload_and_sale.json)

but i think for some reason when i tried to run the code, and i dont know if opensea issue/new update or its my internet connection. when the code enter the opensea link it got this openflare Ddos protection thing that i have to wait for 5 second so its theres a way for me to add delay to the code for the wait? thank you! and here the update of the code.

{
  "nft": [
    {
      "file_path": "C:/Users/Admin/Build/Images/1.png",
      "nft_name": "1",
      "external_link": "",
      "description": "",
      "collection": "Box-Box's Friends",
      "properties": [
        {
          "type": "Background",
          "name": "Gray"
        },
        {
          "type": "Type",
          "name": "Blue"
        },
        {
          "type": "Outfit",
          "name": "Tanktop"
        },
        {
          "type": "Eyes",
          "name": "Sleepy"
        },
        {
          "type": "Eye Brow",
          "name": "Confused"
        },
        {
          "type": "Head",
          "name": "Flower"
        },
        {
          "type": "Mouth",
          "name": "Open"
        }
      ],
      "levels": [],
      "stats": [],
      "unlockable_content": [],
      "explicit_and_sensitive_content": false,
      "supply": 1,
      "blockchain": "Polygon",
      "sale_type": "",
      "price": 0.01,
      "method": "",
      "duration": [
        "25-01-2022 14:00",
        "25-07-2022 15:00"
      ],
      "specific_buyer": "",
      "quantity": "",
      "dna": "a26b3271b9b5a4d071b64a4338de1d3177b4561e",
      "edition": 1,
      "date": 1642979784160,
      "compiler": ""
    ``

**Comment by HiHdrl** [comment]
hi just wanted to say thank you bro it works. and i also promise if my project doing well i'll definitely give you a gift 👍
