### ISSUE TITLE
Error: unexpected keyword argument 'service' Picture attached

### ISSUE THREAD

**Issue by lucasredway** [maximedrn/opensea_automatic_uploader#66]
![Képernyőkép 2022-01-23 111108](https://user-images.githubusercontent.com/56044384/150673755-d193e86d-309b-466e-8750-234e4d4d569f.jpg)

**Comment by maximedrn** [comment]
See this: https://github.com/maximedrn/opensea_automatic_uploader#known-issues-and-important-things-to-know

**Comment by lucasredway** [comment]
> See this: https://github.com/maximedrn/opensea_automatic_uploader#known-issues-and-important-things-to-know

login completed but i getting errors in upload page:

![Képernyőkép 2022-01-23 122437](https://user-images.githubusercontent.com/56044384/150676056-f534ffed-d364-44ad-9e53-200fc5818253.jpg)

**Comment by maximedrn** [comment]
Does the bot go to the Opensea creation URL? Send me an excerpt of your metadata file, the error may come from there.
