### ISSUE TITLE
NFT Price Changes to 1 ETH After Uploading

### ISSUE THREAD

**Issue by atlookat** [maximedrn/opensea_automatic_uploader#71]
I would like to know why is it that whenever I upload an NFT collection onto OpenSea (Polygon Blockchain) the price changes from my original set price to 1 ETH. I was trying to upload a collection and sell it for 0.25 ETH however after I upload it the price automatically changes to 1 ETH. I'm using the latest version of the script 1..4.7, Python v3.9.9. My json file is located just below this text.

{
  "nft": [
    {
      "file_path": "C:/NFT/HeadPotato/build/images/3716.png",
      "nft_name": "HeadPotatoJoe #3716",
      "external_link": "",
      "description": "Your description.",
      "collection": "HeadPotatoJoe",
      "properties": [
        {
          "type": "Background",
          "name": "City"
        },
        {
          "type": "Head",
          "name": "Dark Brown Standard"
        },
        {
          "type": "Mouth",
          "name": "Shining"
        },
        {
          "type": "Eyes",
          "name": "Befudlded"
        },
        {
          "type": "Eyebrows",
          "name": "Monobrow"
        },
        {
          "type": "Nose",
          "name": "No Nose"
        }
      ],
      "levels": [],
      "stats": [],
      "unlockable_content": [],
      "explicit_and_sensitive_content": false,
      "supply": 1,
      "blockchain": "Polygon",
      "price": 0.25,
      "quantity": 1,
      "dna": "f2f9447ec74040f7fe8f5e8eda73bc042e820043",
      "edition": 3716,
      "date": 1642863836959,
      "compiler": "HashLips Art Engine"
    },
    {
      "file_path": "C:/NFT/HeadPotato/build/images/8100.png",
      "nft_name": "HeadPotatoJoe #8100",
      "external_link": "",
      "description": "Your description.",
      "collection": "HeadPotatoJoe",
      "properties": [
        {
          "type": "Background",
          "name": "Space"
        },
        {
          "type": "Head",
          "name": "Orange Standard"
        },
        {
          "type": "Mouth",
          "name": "Beast"
        },
        {
          "type": "Eyes",
          "name": "Neutral"
        },
        {
          "type": "Eyebrows",
          "name": "Raised Mono"
        },
        {
          "type": "Nose",
          "name": "Webbed"
        }
      ],
      "levels": [],
      "stats": [],
      "unlockable_content": [],
      "explicit_and_sensitive_content": false,
      "supply": 1,
      "blockchain": "Polygon",
      "price": 0.25,
      "quantity": 1,
      "dna": "39c52e8a09a03321cfd3d5f79a58edfbb9e04528",
      "edition": 8100,
      "date": 1642863837379,
      "compiler": "HashLips Art Engine"
    }
  ]
}

**Comment by maximedrn** [comment]
The "price" as you said is refer as the quantity in your JSON file. Follow this format please (if you do not need "sale_type", just let it as default):
```json
{
     "nft": [
       {
         "file_path": "",
         "nft_name": "",
         "external_link": "",
         "description": "",
         "collection": "",
         "properties": "",
         "levels": "",
         "stats": "",
         "unlockable_content": "",
         "explicit_and_sensitive_content": "",
         "supply": 1,
         "blockchain": "",
         "sale_type": "",
         "price": 0,
         "method": "",
         "duration": "",
         "specific_buyer": "",
         "quantity": 1
       }
     ]
   }
```

**Comment by maximedrn** [comment]
The Hashlip Compiler does the job at 80% for the metadata file, but my bot requires a different format that is specified in the README file. :/

**Comment by atlookat** [comment]
Many thanks for the prompt reply. I will check it tomorrow, and let you know if it's working.

**Comment by atlookat** [comment]
It's working, thank you @maximedrn

**Comment by maximedrn** [comment]
👍
